
# 1. First create your docker network
 docker network create springappnet
# 2. Create your docker volume
 docker volume create springappvol
# docker-compose.yml 
# DOCKER-COMPOSE FILE

version: '3.1'
services:
  springapp:
    image: mylandmarktech/spring-boot-mongo
    restart: always
    env-file: .env-spring-app
    ports:
      - "8080:8080"
    networks:
      - springappnet
    depends_on:
      mongo
  mongo:
    image: mongo
    env-file: .env-mongodb
    volumes:
      - springappvol:/data/db
    restart: always
    networks:
      - springappnet

volumes:
  springappvol:
    external: true
networks:
  springappnet:
    external: true
